version: '3.1'

services:
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    ports:
      - 9080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: postgres
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_DB_NAME: wordpress
    networks:
      - default

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 6134:5134
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: wordpress
    networks:
      - default

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - default

  node_exporter:
    image: bitnami/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - 9100:9100
    networks:
      - default

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox
    restart: always
    ports:
      - 9115:9115
    volumes:
      - './blackbox.yml:/blackbox.yml'
    command:
      - '--config.file=/blackbox.yml'
    networks:
      - default
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - default

networks:
  default:
    driver: bridge
