global:
  scrape_interval:     5s # Default is every 1 minute.
  evaluation_interval: 5s # Evaluate rules every 15 seconds. The default is every 1 minute.

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090

  - job_name: 'docker_job'
    static_configs:
      - targets: 
        - host.docker.internal:9323
      
  - job_name: 'blackbox_exporter'
    static_configs:
      - targets: 
        - 'blackbox:9115'
  
  - job_name: 'blackbox_exporter_http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: 
        - http://blackbox:9115
        - https://blackbox:9115
        - https://ya.ru
        - https://nixhub.ru
        - http://wordpress:9080
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'postgres'
    static_configs:
      - targets: 
        - db:9187
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: 
        - node_exporter:9100
